CREATE TABLE IF NOT EXISTS public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  comment text not null,
  rating integer not null default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.testimonials
  FOR SELECT USING (true);

-- Allow authenticated users to insert
CREATE POLICY "Enable insert for authenticated users only" ON public.testimonials
  FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'service_role');

-- Allow authenticated users to delete
CREATE POLICY "Enable delete for authenticated users only" ON public.testimonials
  FOR DELETE USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
